### ISSUE TITLE
[Table] Table-view renders only 20 rows

### ISSUE THREAD

**Issue by gavram** [datopian/data-explorer#4] opened 2020-03-02 07:39 UTC
`Table view` renders only 20 rows per page, instead of expected 100 (can be any number).  As a user I want to see all 100 rows per page in table.

Tables look like following example:

https://frontend-national-grid.herokuapp.com/carbon-intensity/historic-generation-mix/r/historic_gb_generation_mix

## Acceptance Criteria

* [ ] `Table view renders all rows per page (in this case 100)

## Tasks

* [ ] Analysis
* TBD...

**Comment by anuveyatsu** [comment] 2020-03-02 12:27
@gavram can you make this issue clear? If this is about scroll bar then we don't need to look at it. If this is about data which is not rendered on the table then it is completely different thing.

**Comment by anuveyatsu** [comment] 2020-03-02 12:28
@gavram I think the screenshot doesn't make a lot of sense here, it doesn't explain anything. A link would be useful.

**Comment by gavram** [comment] 2020-03-02 12:40
@anuveyatsu Do we have a default value for number of rows that are showing in `Table view`. The default `pagination` from `react-tables-v6` has option to choose from drop-down, the number of rows that are showing. In other projects and in earlier versions of `data-explorer` I saw that there are usually shown 100 rows.

**Comment by anuveyatsu** [comment] 2020-03-03 03:44
@gavram the description of this issue is still misleading. The problem isn't with scroll bar. Could you please fix it asap?

We don't need to know default number of rows in table view - it should render any number of rows you pass. The pagination is implemented separately so it is irrelevant here.

**Comment by gavram** [comment] 2020-03-03 07:45
@anuveyatsu I missed the point. The real issue here is that `Table view` do not render all expected 100 rows per page, but only 20. I removed issue with scroll bar from the description, because it is not a real issue and can be resolved separate from this.

**Comment by anuveyatsu** [comment] 2020-03-07 03:51
FIXED in https://github.com/datopian/datapackage-views-js/commit/dbb9eb35a7f0aa6f8577bb1968a2d3b7a803a035 and available in `datapackage-views-js@1.3.6`

**Closed by anuveyatsu** 2020-03-07 03:51 UTC
